DROP DATABASE IF EXISTS many_steps;
-- 建表
CREATE DATABASE many_steps DEFAULT CHARACTER SET utf8;

-- 用户表
CREATE TABLE USER(
id INT(11) NOT NULL AUTO_INCREMENT,
NAME VARCHAR(255) DEFAULT NULL,
headimageurl VARCHAR(255) DEFAULT NULL,
openid VARCHAR(255) DEFAULT NULL,
unionid VARCHAR(255) DEFAULT NULL,
phone VARCHAR(255) DEFAULT NULL,
createdate LONG DEFAULT NULL,
steps_total VARCHAR(255) DEFAULT NULL,
energy_total VARCHAR(255) DEFAULT NULL,
PRIMARY KEY(id)
)ENGINE=INNODB DEFAULT CHARSET=utf8;

-- 步数记录表
CREATE TABLE stepsrecord(
id INT(11) NOT NULL AUTO_INCREMENT,
uid INT(11) DEFAULT NULL,
steps INT(11) DEFAULT NULL,
createdate LONG DEFAULT NULL,
PRIMARY KEY (id),
CONSTRAINT fk_stepsrecord_USER FOREIGN KEY (uid) REFERENCES USER (id)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

-- 步数金币表
CREATE TABLE stepscoin(
id INT(11) NOT NULL AUTO_INCREMENT,
uid INT(11) DEFAULT NULL,
coin INT(11) DEFAULT NULL,
createdate LONG DEFAULT NULL,
PRIMARY KEY (id),
CONSTRAINT fk_stepscoin_USER FOREIGN KEY (uid) REFERENCES USER (id)
) ENGINE=INNODB DEFAULT CHARSET=utf8;