`many_steps``many_steps``many_steps`DROP DATABASE IF EXISTS many_steps;
-- 建表
CREATE DATABASE many_steps DEFAULT CHARACTER SET utf8;

-- 用户表
CREATE TABLE USER(
id INT(11) NOT NULL AUTO_INCREMENT,
NAME VARCHAR(255) DEFAULT NULL,
headimageurl VARCHAR(255) DEFAULT NULL,
openid VARCHAR(255) DEFAULT NULL,
unionid VARCHAR(255) DEFAULT NULL,
session_key VARCHAR(255) DEFAULT NULL,
access_token VARCHAR(255) DEFAULT NULL,
phone VARCHAR(255) DEFAULT NULL,
createdate VARCHAR(20) DEFAULT NULL,
steps_total VARCHAR(255) DEFAULT NULL,
energy_total VARCHAR(255) DEFAULT NULL,
PRIMARY KEY(id)
)ENGINE=INNODB DEFAULT CHARSET=utf8;

-- 地址表
CREATE TABLE address(
id INT(11) NOT NULL AUTO_INCREMENT,
uid INT(11) DEFAULT NULL,
receiver VARCHAR(20) DEFAULT NULL,
mobile VARCHAR(20) DEFAULT NULL,
post VARCHAR(20) DEFAULT NULL,
createdate VARCHAR(20) DEFAULT NULL,
PRIMARY KEY (id),
CONSTRAINT fk_address_USER FOREIGN KEY (uid) REFERENCES USER (id)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

-- 步数记录表
CREATE TABLE stepsrecord(
id INT(11) NOT NULL AUTO_INCREMENT,
uid INT(11) DEFAULT NULL,
steps INT(11) DEFAULT NULL,
createdate VARCHAR(20) DEFAULT NULL,
PRIMARY KEY (id),
CONSTRAINT fk_stepsrecord_USER FOREIGN KEY (uid) REFERENCES USER (id)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

-- 步数金币表
CREATE TABLE stepscoin(
id INT(11) NOT NULL AUTO_INCREMENT,
uid INT(11) DEFAULT NULL,
coin INT(11) DEFAULT NULL,
rundate VARCHAR(20) DEFAULT NULL,
convertsteps INT(11) DEFAULT NULL,
createdate VARCHAR(20) DEFAULT NULL,
PRIMARY KEY (id),
CONSTRAINT fk_stepscoin_USER FOREIGN KEY (uid) REFERENCES USER (id)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

-- 商品表
CREATE TABLE product(
id INT(11) NOT NULL AUTO_INCREMENT,
NAME VARCHAR(50) DEFAULT NULL,
coin INT(11) DEFAULT NULL,
price FLOAT DEFAULT NULL,
stock INT(11) DEFAULT NULL,
subTitle VARCHAR(255) DEFAULT NULL,
imageurl VARCHAR(255) DEFAULT NULL,
convertsteps INT(11) DEFAULT NULL,
createdate VARCHAR(20) DEFAULT NULL,
PRIMARY KEY (id)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

-- 订单表
CREATE TABLE order_(
id INT(11) NOT NULL AUTO_INCREMENT,
uid INT(11) DEFAULT NULL,
pid INT(11) DEFAULT NULL,
adid INT(11) DEFAULT NULL,
STATUS VARCHAR(255) DEFAULT NULL,
ordercode VARCHAR(50) DEFAULT NULL,
couriernumber VARCHAR(50) DEFAULT NULL,
createdate VARCHAR(20) DEFAULT NULL,
PRIMARY KEY (id),
CONSTRAINT fk_order__USER FOREIGN KEY (uid) REFERENCES USER (id)
) ENGINE=INNODB DEFAULT CHARSET=utf8;